// `npm run fsm:export`: turn every transition table into a mermaid diagram, written to
// docs/diagrams/<name>.md (and printed). The tables in code are the source of truth.
import { mkdirSync, writeFileSync } from "node:fs";
import { busFsm } from "@/bus/server";
import { coreFsm } from "@/core/cpu-core";
import type { Fsm } from "@/core/fsm";
import { processFsm } from "@/core/scheduler";
import { PERIPHERALS } from "@/components/peripherals/index";

const machines: Array<[string, Fsm<string>]> = [
  ["cpu-core", coreFsm],
  ["process", processFsm],
  ["bus", busFsm],
  ...PERIPHERALS.map((p): [string, Fsm<string>] => [p.kind, p.fsm]),
];

mkdirSync("docs/diagrams", { recursive: true });
for (const [name, fsm] of machines) {
  let diagram: string;
  try {
    diagram = fsm.toMermaid();
  } catch (error) {
    console.error(`fsm:export needs toMermaid() in core/fsm.ts, a stretch module you haven't built yet (${(error as Error).message}).`);
    process.exit(1);
  }
  writeFileSync(`docs/diagrams/${name}.md`, `# ${fsm.name}\n\nGenerated by \`npm run fsm:export\` from the transition table in code.\n\n\`\`\`mermaid\n${diagram}\n\`\`\`\n`);
  console.log(`## ${fsm.name}\n${diagram}\n`);
}
console.log(`wrote ${machines.length} diagrams to docs/diagrams/`);
