// `npm run programs`: copy programs/*.asm into programs/bundle.ts, so code that can't read files
// (the board running in a web page, the peripheral host) still has every program's source.
// It runs before `npm run dev` and `npm run build`; run it yourself after editing a .asm file.
//   --check   don't write; exit 1 if programs/bundle.ts is out of date
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

export const BUNDLE_FILE = "programs/bundle.ts";

/** The bundle's text for a set of .asm files (name -> source). */
export function renderBundle(sources: ReadonlyMap<string, string>): string {
  const entries = [...sources].sort(([a], [b]) => a.localeCompare(b)).map(([file, source]) => `  ${JSON.stringify(file)}: ${JSON.stringify(source)},`);
  return [
    "// Generated by `npm run programs` from programs/*.asm. Don't edit this file: edit the .asm",
    "// files and run `npm run programs` again (it also runs before `npm run dev` and `npm run build`).",
    "export const PROGRAM_SOURCES: Readonly<Record<string, string>> = {",
    ...entries,
    "};",
    "",
  ].join("\n");
}

/** Every programs/*.asm file in a folder. */
export function readSources(dir = "programs"): Map<string, string> {
  return new Map(
    readdirSync(dir)
      .filter((file) => file.endsWith(".asm"))
      .map((file) => [file, readFileSync(join(dir, file), "utf8")]),
  );
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const text = renderBundle(readSources());
  if (process.argv.includes("--check")) {
    const current = readFileSync(BUNDLE_FILE, "utf8");
    if (current !== text) {
      console.error(`${BUNDLE_FILE} is out of date: run npm run programs`);
      process.exit(1);
    }
    console.log(`${BUNDLE_FILE} is up to date`);
  } else {
    writeFileSync(BUNDLE_FILE, text);
    console.log(`wrote ${BUNDLE_FILE}`);
  }
}
